use_frameworks!

platform :ios, '8.0'

target 'MTTrackKit_Example' do
  pod 'MTTrackKit', :path => '../'

  target 'MTTrackKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
